export const countries = [
  { name: "Indonesia", code: "+62", emoji: "🇮🇩" },
  { name: "Singapore", code: "+65", emoji: "🇸🇬" },
  { name: "Malaysia", code: "+60", emoji: "🇲🇾" },
  { name: "Philippines", code: "+63", emoji: "🇵🇭" },
  { name: "Thailand", code: "+66", emoji: "🇹🇭" },
  { name: "Vietnam", code: "+84", emoji: "🇻🇳" },
  { name: "Japan", code: "+81", emoji: "🇯🇵" },
  { name: "South Korea", code: "+82", emoji: "🇰🇷" },
  { name: "China", code: "+86", emoji: "🇨🇳" },
  { name: "India", code: "+91", emoji: "🇮🇳" },
  { name: "United States", code: "+1", emoji: "🇺🇸" },
  { name: "United Kingdom", code: "+44", emoji: "🇬🇧" },
  { name: "Australia", code: "+61", emoji: "🇦🇺" },
  { name: "Canada", code: "+1", emoji: "🇨🇦" },
  { name: "Germany", code: "+49", emoji: "🇩🇪" },
  { name: "France", code: "+33", emoji: "🇫🇷" },
  { name: "Netherlands", code: "+31", emoji: "🇳🇱" },
  { name: "Saudi Arabia", code: "+966", emoji: "🇸🇦" },
  { name: "United Arab Emirates", code: "+971", emoji: "🇦🇪" },
  { name: "Brazil", code: "+55", emoji: "🇧🇷" },
];
